# Generated by Django 3.2.16 on 2022-12-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
    ]
