# Generated by Django 3.2.16 on 2022-12-12 20:02

from django.db import migrations, models
import gestao_rh.documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default='', upload_to=gestao_rh.documentos.models.arquivo_documento_directory_path),
        ),
    ]
